// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GrNMF
List GrNMF(NumericMatrix Xr, NumericMatrix Wr, int k = 5, int lambda = 100, int n_iter = 5000, double converge = 1e-6);
RcppExport SEXP GrNMF_GrNMF(SEXP XrSEXP, SEXP WrSEXP, SEXP kSEXP, SEXP lambdaSEXP, SEXP n_iterSEXP, SEXP convergeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type Wr(WrSEXP );
        Rcpp::traits::input_parameter< int >::type k(kSEXP );
        Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP );
        Rcpp::traits::input_parameter< double >::type converge(convergeSEXP );
        List __result = GrNMF(Xr, Wr, k, lambda, n_iter, converge);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
